# ── App ──────────────────────────────────────────
spring.application.name=payflow

# ── Database ─────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/payflow
spring.datasource.username=postgres
spring.datasource.password=Vamshi@1104
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ───────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ── Server ────────────────────────────────────────

# ── Redis ─────────────────────────────────────────
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

server.port=8081

# ── JWT ───────────────────────────────────────────
jwt.secret=payflow_super_secret_key_change_this_in_production_min_256_bits
jwt.expiration=86400000


# ── Rate Limiting ─────────────────────────────────
rate.limit.requests=60
rate.limit.window=60


# ── Kafka ─────────────────────────────────────────
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=payflow-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.max.block.ms=5000
spring.kafka.producer.properties.request.timeout.ms=5000
spring.kafka.consumer.properties.session.timeout.ms=15000